[project1]
path=/path/ke/project1
db_user=root
db_password=mysql
db_host=localhost
db_port=3306
db_name=dbproject1
exclude=node_modules,.git,tmp,cache,vendor,.idea,storage/framework,storage/logs


[project2]
path=/path/ke/project2
db_user=root
db_password=mysql
db_host=localhost
db_port=3306
db_name=dbproject2
exclude=node_modules,.git,tmp,cache,vendor,.idea,storage/framework,storage/logs
